name: nocturnal
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
   - family:  Nocons
     fonts:
      - asset: fonts/Nocons.ttf